import 'bootstrap/dist/css/bootstrap.css';
import './css/style.css'
import BootstrapClient from '@/components/Bootstrap/BootstrapClient';

export const metadata = {
    title: 'Welcome Pets',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}) {
    return (
        <html lang="en">
            <body>
                {children}
                <BootstrapClient />
            </body>
        </html>
    );
}