import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import Navbar from '@/components/navbar';
import Home from "./home";

export const metadata = {
    title: 'Welcome Pets',
    description: 'Generated by create next app',
}

export default function RootLayout({
    children,
}) {
    return (
        <ClerkProvider>
            <html lang="en">
                <body>
                    <Navbar />
                    {children}
                </body>
            </html>
        </ClerkProvider>
    );
}
