import { Inter } from 'next/font/google'
import 'bootstrap/dist/css/bootstrap.css';
import './globals.css'
import BootstrapClient from '@/components/Bootstrap/BootstrapClient';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Welcome Pets',
    description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                {children}
                <BootstrapClient />
            </body>
        </html>
    )
}
